Exercicios


1 - Selecione todos os valores ímpares do seguinte array:
array = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
import numpy as np

a = np.array( [1, 2, 3, 4, 5, 6, 7, 8, 9])

np.where(a%2== 1)

(array([0, 2, 4, 6, 8], dtype=int64),)

2 - Substitua os valores ímpares do seguinte array por 0:
array = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
a = np.array( [1, 2, 3, 4, 5, 6, 7, 8, 9])

np.where(a%2== 1 , 0, a)

array([0, 2, 0, 4, 0, 6, 0, 8, 0])

Utilizando o método np.genfromtxt(), importe as 4 primeiras colunas do dataset do íris e print as 10 primeiras linhas

In [13]:
filedata = np.genfromtxt('iris.data', delimiter=',', usecols=[0,1,2,3])

In [17]:
filedata[0:10,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

4 - Calcule a média, mediana e desvio padrão da coluna sepallenght

In [19]:
np.mean(filedata[:,1], axis=0)

3.0540000000000003

In [20]:
np.std(filedata[:,1], axis=0)

0.4321465800705435

In [21]:
np.median(filedata[:,1], axis=0)

3.0

5 - Filtre a matriz para conter apenas dados nos quais petallength (3ª coluna) > 1.5 e sepallength (1ª coluna) < 5.0

In [37]:
np.where((filedata[:3] >1.0) & (filedata[:1] < 5.0))



(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([1, 2, 1, 2, 1, 2], dtype=int64))

6 - Esse dataset possui nans?

In [35]:
filedata2 = np.genfromtxt('iris.data', delimiter=',')
np.isnan(filedata2).sum()

150

7 - Crie uma coluna de volume sabendo que ele pode ser calculado por (pi x petallength x sepal_length^2)/3

In [48]:
volume =  (3.14 * filedata[:,3] *  (filedata[:,1]**2))/3

volume = volume.reshape(len(volume), 1)
filedata2 = np.append(filedata,volume, axis=1)

print(filedata2)

[[ 5.1         3.5         1.4         0.2         2.56433333]
 [ 4.9         3.          1.4         0.2         1.884     ]
 [ 4.7         3.2         1.3         0.2         2.14357333]
 [ 4.6         3.1         1.5         0.2         2.01169333]
 [ 5.          3.6         1.4         0.2         2.71296   ]
 [ 5.4         3.9         1.7         0.4         6.36792   ]
 [ 4.6         3.4         1.4         0.3         3.62984   ]
 [ 5.          3.4         1.5         0.2         2.41989333]
 [ 4.4         2.9         1.4         0.2         1.76049333]
 [ 4.9         3.1         1.5         0.1         1.00584667]
 [ 5.4         3.7         1.5         0.2         2.86577333]
 [ 4.8         3.4         1.6         0.2         2.41989333]
 [ 4.8         3.          1.4         0.1         0.942     ]
 [ 4.3         3.          1.1         0.1         0.942     ]
 [ 5.8         4.          1.2         0.2         3.34933333]
 [ 5.7         4.4         1.5         0.4         8.10